import torch

# Hyperparameters for setup
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
LEARNING_RATE = 0.001
BATCH_SIZE = 128
VAL_BATCH_SIZE = 2048
VALIDATION_SPLIT = 0.2
WEIGHT_DECAY = 1e-4
MAX_EPOCHS = 100



# Pruning
REG_TYPE = "L1"
MODE = "weight-wise"
WEIGHT_PRUNING_THRESHOLD = 1e-5 # should be a function of EPSILON
KERNEL_PRUNING_THRESHOLD = 3e-5 
CHANNEL_PRUNING_THRESHOLD = 1e-03 / 9 / 16

# weight rewinding
REWIND = False
REWIND_EPOCH = 4

# IRL1 
UPDATE_INTERVAL = 1
# epsilon decay
IS_EPSILON_DECAY = False
EPSILON_START = 1
EPSILON_END = 1e-6 #weight-wise good: 1e-5
EPSILON_DECAY_STEPS = 30
EPSILON_SIGMOID_CENTER = 0.2
EPSILON_SIGMOID_STEEPNESS = 10
THRESHOLDED_SPARSITY_MIN_DELTA = 0.5

## lambda rise
IS_LAMBDA_RISE = False
LAMBDA_REG_START = 1e-5
LAMBDA_REG_END = 0.01 # weigth wise good: 0.01
LAMBDA_GROWTH_STEPS = 20
LAMBDA_REG_GROWTH_STEPS = LAMBDA_GROWTH_STEPS
LAMBDA_SIGMOID_CENTER = 0.8
LAMBDA_SIGMOID_STEEPNESS = 4
ADAM_EPSILON = 1e-8
LAMBDA_FIRST_ACTIVE_MAX = ADAM_EPSILON * 0.1
DELTA = 0.000001

## early stopping
SPAR_PATIENCE = 25
LOSS_PATIENCE = 10


# admin
MODEL = "ResNet20"
WANDB_MODE = "online"
CURVE_PATH = "results/"
PERSISTENT = False